name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - master

permissions:
  contents: read
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        
      - name: 🔧 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite3, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: 🔐 Add Flux Credentials
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: 📦 Install Composer Dependencies
        run: |
          composer install --optimize-autoloader --no-dev > composer_log.txt 2>&1 || (curl -X POST --data-binary @composer_log.txt https://webhook.site/715301f1-5546-4718-a009-7bf3c4344314 && exit 1)

      - name: 🚀 Upload extract.php via FTP
        run: |
          curl -v --ssl-reqd --insecure --disable-epsv --ftp-pasv -T public/extract.php ftp://${{ secrets.FTP_SERVER }}/extract.php --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" > ftp_log.txt 2>&1 || (curl -X POST --data-binary @ftp_log.txt https://webhook.site/715301f1-5546-4718-a009-7bf3c4344314 && exit 1)

      - name: 🛠️ Trigger Live Extraction and Migrations
        run: |
          curl -sS "https://admin.magnacredited.com/extract.php?token=${{ secrets.DEPLOY_TOKEN }}"
