name: Deploy to cPanel via Pull

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🚀 Upload extract.php via FTP
        run: |
          curl -sS --ssl-reqd --insecure --disable-epsv --ftp-pasv -T public/extract.php ftp://${{ secrets.FTP_SERVER }}/extract.php --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"

      - name: 🛠️ Trigger Live Extraction and Migrations
        run: |
          curl -sS "https://admin.magnacredited.com/extract.php?token=${{ secrets.DEPLOY_TOKEN }}"
